name: Build and Test Part 3

on: [push, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Install Utilities and Compilers
      run: |
        # Install utilities and GCC
        sudo apt update
        sudo apt install -y make gcc

    - name: Test if the 'ish2' Directory is Present
      run: |
        # Check 'ish2'
        if [ ! -d 'ish2' ]
        then
          echo -e "The 'ish2' directory is missing."
          exit 1
        fi

    - name: Test if the Makefile is Present and Correct
      working-directory: ${{github.workspace}}/ish2
      run: |
        # Check Makefile
        if [ ! -f 'Makefile' ]
        then
          echo -e 'The Makefile file is missing.'
          exit 1
        fi
        HASH_OUTPUT="$(sha256sum 'Makefile')"
        CORRECT_HASH_OUTPUT='4d10a7d915480f58814aa397ed4d8ea5666788ede59e4e0fb2f3d539185cd204  Makefile'
        if [ "$HASH_OUTPUT" != "$CORRECT_HASH_OUTPUT" ]
        then
          echo -e "The Makefile file is incorrect. Do not change the build file for 'ish2'."
          exit 1
        fi

    - name: Compile The Second Version of the Shell
      working-directory: ${{github.workspace}}/ish2
      run: |
        # Build
        make clean
        make

        if [ ! -f ./ish ]
        then
          echo -e "The 'ish' executable was not generated."
          exit 1
        fi

    - name: Run and Test The Second Version of the Shell with Test Input 1
      working-directory: ${{github.workspace}}/ish2
      run: |
        # Run and Test
        TARGET='ish'

        if [ ! -f ./"$TARGET" ]
        then
          echo -e "The '$TARGET' executable is missing."
          exit 1
        fi

        read -r -d '' CORRECT_OUTPUT <<-'EOF' || true
        world

        EOF

        rm -f 'world.txt'
        OUTPUT="$(echo 'echo world | cat | cat > world.txt' | ./"$TARGET")"
        if [ $? -ne 0 ]
        then
          echo -e "The program '$TARGET' failed to run successfully."
          exit 1
        fi
        OUTPUT="$(cat < 'world.txt')"

        if ! diff --strip-trailing-cr <(echo "$OUTPUT") <(echo "$CORRECT_OUTPUT") &>/dev/null
        then
          echo -e "The program '$TARGET' failed to generate the correct output (at least a single or more characters are not exact).\n\n" \
                  'The program output:\n\n' \
                  '```\n'                   \
                  "$OUTPUT"                 \
                  '\n```\n\n'               \
                  'The correct output:\n\n' \
                  '```\n'                   \
                  "$CORRECT_OUTPUT"         \
                  '\n```\n\n'               \
                  'The diff:\n\n'           \
                  '```diff' | sed 's/^ *//g'
          diff --strip-trailing-cr <(echo "$OUTPUT") <(echo "$CORRECT_OUTPUT")
          echo -e '\n```\n' | sed 's/^ *//g'
          exit 1
        fi

        echo -e "The program '$TARGET' successfully generated the correct output for Test Input 1."

    - name: Run and Test The Second Version of the Shell with Test Input 2
      working-directory: ${{github.workspace}}/ish2
      run: |
        # Run and Test
        TARGET='ish'

        if [ ! -f ./"$TARGET" ]
        then
          echo -e "The '$TARGET' executable is missing."
          exit 1
        fi

        read -r -d '' CORRECT_OUTPUT <<-'EOF' || true
        world

        EOF

        rm -f 'end.txt'
        OUTPUT="$(echo 'cat < world.txt | cat | cat | cat | cat > end.txt' | ./"$TARGET")"
        if [ $? -ne 0 ]
        then
          echo -e "The program '$TARGET' failed to run successfully."
          exit 1
        fi
        OUTPUT="$(cat < 'end.txt')"

        if ! diff --strip-trailing-cr <(echo "$OUTPUT") <(echo "$CORRECT_OUTPUT") &>/dev/null
        then
          echo -e "The program '$TARGET' failed to generate the correct output (at least a single or more characters are not exact).\n\n" \
                  'The program output:\n\n' \
                  '```\n'                   \
                  "$OUTPUT"                 \
                  '\n```\n\n'               \
                  'The correct output:\n\n' \
                  '```\n'                   \
                  "$CORRECT_OUTPUT"         \
                  '\n```\n\n'               \
                  'The diff:\n\n'           \
                  '```diff' | sed 's/^ *//g'
          diff --strip-trailing-cr <(echo "$OUTPUT") <(echo "$CORRECT_OUTPUT")
          echo -e '\n```\n' | sed 's/^ *//g'
          exit 1
        fi

        echo -e "The program '$TARGET' successfully generated the correct output for Test Input 2."

